project:
  type: website
  output-dir: C:\Users\mtstaple.stu\Documents\GitHub\E-Portfolio_MS

website:
  navbar:
    left:
      - href: index.qmd
      - href: resume2.qmd
        text: Resume
      - href: skills.qmd
        text: Skills Summary
      - href: academic_work.qmd
        text: Academic Work

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

