---
title: "Academic Work"
format:
  html:
    theme: yeti
    css: styles.css
    toc: true
mainfont: Perpetua Titling MT
sansfont: Cambria
monofont: Cambria
header-includes:
  - \usepackage{pdfpages}
---

Below is a sample of some of my academic work completed in my Bachelor's, Certificate and Master's Programs.

# Code Samples

# **Will changes to the shoreline vegetation due to the new reservoir for the Site C Dam impact the shoreline stability and health of the riparian zone along the Peace River in British Columbia between the Moberly River and Cache Creek**

\\includepdf\[pages={-}\]{GEM500Proposal_2_06Dec2025.pdf}

# Identifying the Change in Vegetation Health and Density After the 2016 Forest Fire in Fort McMurray, ALberta, Specifically Within the Boundary of the Horse River Fire

\\includepdf\[pages={-}{Stapleton.CODG135.TermProject.Report}

# Clean Drinking Water Distribution Network

\\includepdf\[pages={-}{Stapleton.CODG123.ConceptualUtilityNetwork}

# Application of GIS in the Planning, Response and Recovery Stages of the Disaster Response and Management of Wildfires

\\includepdf\[pages={-}\]{Stapleton.CODG126.WildFire.Report}

# Comparison of MVT and Irish-Type Deposits

\\includepdf\[pages={-}\]{GEOL 462.Seminar.Final.pdf}
